import { CSSProperties } from 'react';

const LoginStyles: { [key: string]: CSSProperties } = {
    buttonContainer: {
        display: 'flex',
        gap: '10px',
    },
    container: {
        display: 'flex',
        flexDirection: 'row',
        minHeight: '100vh',
        backgroundColor: '#f5f5f5',
        fontFamily: 'Calibri, Arial, sans-serif',
        margin: 0,
        padding: 0,
        overflow: 'hidden',
    },
    createAccount: {
        padding: '10px 20px',
        backgroundColor: '#1e4d04',
        color: 'white',
        border: 'none',
        borderRadius: '20px',
        fontSize: '14px',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
    credentialsText: {
        fontSize: '16px',
        color: '#666',
        textAlign: 'center',
        margin: '0 0 30px 0',
    },
    footer: {
        position: 'absolute',
        bottom: '10px',
        right: '0px',
        left: '0px',
        fontSize: '18px',
        color: '#1e4d04',
        textAlign: 'center',
        padding: '0 10px 10px 650px',
    },
    formGroup: {
        marginBottom: '20px',
        width: '100%',
        maxWidth: '300px',
    },
    input: {
        width: '100%',
        padding: '10px',
        border: 'none',
        backgroundColor: '#e5ffe3',
        borderRadius: '4px',
        fontSize: '14px',
        boxSizing: 'border-box',
    },
    label: {
        display: 'block',
        marginBottom: '8px',
        fontSize: '14px',
        color: '#1e4d04',
        fontWeight: 'bold',
    },
    loginButton: {
        padding: '10px 20px',
        backgroundColor: '#1e4d04',
        color: 'white',
        border: 'none',
        borderRadius: '20px',
        fontSize: '14px',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
    logoBox: {
        backgroundColor: '#1e4d04',
        padding: '20px 40px',
        borderRadius: '5px',
        textAlign: 'center',
    },
    logoContainer: {
        flex: 1,
        backgroundColor: '#1e4d04',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginForm: {
        flex: 1,
        backgroundColor: 'white',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '40px',
    },
    logoImage: {
        width: '100%',
        maxWidth: '500px',
        height: 'auto', 
    },
    logoSubtext: {
        fontSize: '28px',
        color: '#ffffff',
        margin: '5px 0 0 0',
        fontStyle: 'italic',
        fontWeight: 'bold',
    },
    logoText: {
        fontSize: '32px',
        fontWeight: 'bold',
        color: '#333',
        margin: 0,
    },
    welcomeText: {
        fontSize: '40px',
        fontWeight: 'normal',
        color: '#1e4d04',
        textAlign: 'center',
        margin: '0 0 70px 0',
    },
};

export default LoginStyles;