import { CSSProperties } from 'react';

const OfferApplicantsStyles: { [key: string]: CSSProperties } = {
  applicantsButton: {
    backgroundColor: '#1e4d04',
    border: '1px solid #1e4d04',
    color: '#ffffff',
    padding: '5px 10px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  applyButton: {
    backgroundColor: '#ffffff',
    border: '1px solid #1e4d04',
    color: '#1e4d04',
    padding: '5px 10px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  boxTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    margin: '10px 0 5px 0', 
    marginBottom: '15px',
    color: '#1e4d04',
    textAlign: 'center',
  },
  boxIsInternship: { 
    fontFamily: 'sans-serif', 
    fontSize: '14px', 
    fontWeight: 'bold', 
    color: '#1e4d04' 
  },
  companyLogo: {
    width: '50px',
    height: 'auto',
  },
  container: {
    display: 'flex',
    flexDirection: 'row',
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    fontFamily: 'Calibri, Arial, sans-serif',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
  },
  createJobContainer: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(0,0,0,0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  createJobButton: {
    border: '1px solid #1e4d04',
    padding: '5px 10px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px', 
    backgroundColor: '#1e4d04', 
    color: 'white',
  },
  createJobPopup: {
    background: 'white',
    padding: '30px',
    borderRadius: '10px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.2)',
    minWidth: '350px',
    maxWidth: '90vw',
  },
  jobCard: {
    backgroundColor: 'white',
    padding: '20px',
    borderRadius: '5px',
    marginBottom: '20px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    border: '1px solid #1e4d04',
  },
  jobDescription: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#8b8b8b',
    margin: '10px 0',
  },
  jobType: {
    backgroundColor: '#ffffff',
    border: '1px solid #1e4d04',
    color: '#1e4d04',
    padding: '5px 10px',
    borderRadius: '4px',
    fontSize: '14px',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 'bold',
  },
  jobHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  jobLocation: {
    fontSize: '16px',
    color: '#1e4d04',
    margin: '2px 0',
  },
  jobRequirements: {
    fontSize: '14px',
    color: '#8b8b8b',
    margin: '0 0 10px 20px',
  },
  jobSubtitle: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#8b8b8b',
    margin: '10px 0 5px 0',
  },
  jobTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#1e4d04',
    margin: 0,
  },
  logoContainer: {
    marginBottom: '20px',
  },
  logoImage: {
    width: '180px',
    height: 'auto',
    cursor: 'pointer',
  },
  logoutButton: {
    width: '80%',
    padding: '10px',
    backgroundColor: 'white',
    color: '#1e4d04',
    border: 'none',
    borderRadius: '20px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    position: 'absolute',
    bottom: '50px',
    left: '50%',
    transform: 'translateX(-50%)',
    marginTop: 0,
  },
  mainContent: {
    marginLeft: '250px',
    padding: '20px',
    flex: 1,
    backgroundColor: '#f5f5f5',
    overflowY: 'auto',
  },
  searchContainer: {
    width: '80%',
    marginBottom: '20px',
  },
  searchInput: {
    width: '100%',
    padding: '10px',
    border: 'none',
    backgroundColor: '#e5ffe3',
    borderRadius: '20px',
    fontSize: '14px',
    boxSizing: 'border-box',
  },
  sectionNoApplicants: {
    textAlign: 'center',
    fontSize: '20px',
    color: '#5b5b5b',
    fontWeight: 'bold',
  },
  sectionSubtitle: {
    textAlign: 'center',
    fontSize: '16px',
    color: '#1e4d04',
    marginBottom: '20px',
  },
  sectionTitle: {
    textAlign: 'center',
    fontSize: '40px',
    fontWeight: 'bold',
    color: '#1e4d04',
    marginBottom: '20px',
  },
  sidebar: {
    position: 'fixed',
    width: '250px',
    height: '100vh',
    backgroundColor: '#1e4d04',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '20px 0',
  },
  sidebarButton: {
    width: '80%',
    padding: '10px',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    borderRadius: '20px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginBottom: '10px',
    textAlign: 'center',
  },
  userData: {
    color: 'white',
    fontSize: '14px',
    margin: '5px 0 0 0',
  },
  userName: {
    color: 'white',
    fontSize: '16px',
    fontWeight: 'bold',
    margin: 0,
  },
  userPhoto: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    marginBottom: '10px',
  },
  userProfile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '20px',
  },
};

export default OfferApplicantsStyles;